seed: 1
device: "cuda"
wandb_project_name: "Amyloid-test"
run_name: "baseline_new_prompt"

data:
  train_file_path: "/home/damian/projects/Deepskim/dataset/train_data.csv"
  val_file_path: "/home/damian/projects/Deepskim/dataset/val_data.csv"
  test_file_path: "/home/damian/projects/Deepskim/dataset/test_data.csv"
  target: "labels"
  seed: 1
  eos_token: </s>

model:
  model_name: "BioMistral/BioMistral-7B"
  change_classifier: false
  torch_dtype: "bfloat16"
  device_map: "auto"

  # QLoRA quantization settings
  load_in_4bit: true
  bnb_4bit_quant_type: "nf4"       # best for QLoRA
  bnb_4bit_use_double_quant: true
  bnb_4bit_compute_dtype: "bfloat16"

peft:
  method: "lora"
  lora_config:
      lora_alpha: 32
      lora_dropout: 0.2
      r: 16
      bias: "none"
      task_type: "CAUSAL_LM"
      target_modules: 
      - "q_proj"
      - "k_proj"
      - "v_proj"
      - "o_proj"
      - "gate_proj"
      - "up_proj"
      - "down_proj"

  sft_config:
      output_dir: "qlora_biomistral"
      num_train_epochs: 3
      per_device_train_batch_size: 4
      per_device_eval_batch_size: 4
      eval_strategy: "steps"
      eval_accumulation_steps: 1
      gradient_accumulation_steps: 4
      optim: "paged_adamw_32bit"
      save_steps: 50
      save_total_limit: 10
      logging_steps: 10
      eval_steps: 15
      learning_rate: 0.000025
      weight_decay: 0.001
      fp16: False
      bf16: True
      max_grad_norm: 0.3
      max_steps: -1
      warmup_ratio: 0.03
      group_by_length: True
      lr_scheduler_type: "cosine"
      report_to: "wandb"
      run_name: null
      max_length: null
      save_strategy: "steps"
      hub_strategy: "every_save"
      push_to_hub: False
      hub_model_id: tmp
      hub_private_repo: True
      completion_only_loss: True
      batch_eval_metrics: True

evaluation:
  decision_threshold: 0.5
