seed: 1
device: "cuda"
wandb_project_name: "Amyloid-test"
run_name: "Mar10_decision_abstract_promptshort"

data:
  train_file_path: "/home/damian/projects/Deepskim/dataset/data_abstract_only/train_data.csv"
  val_file_path: "/home/damian/projects/Deepskim/dataset/data_abstract_only/val_data.csv"
  test_file_path: "/home/damian/projects/Deepskim/dataset/data_abstract_only/test_data.csv"
  target: "labels"
  seed: 1
  eos_token: null
  max_abstract_len: 400
  positive_ratio: 0.3

model:
  model_name: "BioMistral/BioMistral-7B"
  change_classifier: false
  torch_dtype: "bfloat16"
  device_map: "auto"

  # QLoRA quantization settings
  load_in_4bit: true
  bnb_4bit_quant_type: "nf4"       # best for QLoRA
  bnb_4bit_use_double_quant: true
  bnb_4bit_compute_dtype: "bfloat16"

peft:
  method: "lora"
  lora_config:
      lora_alpha: 64
      lora_dropout: 0.2
      r: 16
      bias: "none"
      task_type: "CAUSAL_LM"
      target_modules: 
      - "q_proj"
      - "k_proj"
      - "v_proj"
      - "o_proj"
      - "gate_proj"
      - "up_proj"
      - "down_proj"

  sft_config:
      output_dir: "Mar10_decision_abstract_promptshort"
      num_train_epochs: 7
      per_device_train_batch_size: 8
      per_device_eval_batch_size: 4
      eval_strategy: "steps"
      eval_accumulation_steps: 1
      gradient_accumulation_steps: 2
      optim: "paged_adamw_8bit"
      save_steps: 20
      save_total_limit: 30
      logging_steps: 5
      eval_steps: 20
      learning_rate: 0.0001
      weight_decay: 0.01
      fp16: False
      bf16: True
      max_grad_norm: 1
      max_steps: -1
      warmup_ratio: 0.03
      group_by_length: False
      lr_scheduler_type: "cosine"
      report_to: "wandb"
      run_name: null
      max_length: null
      save_strategy: "steps"
      hub_strategy: "every_save"
      push_to_hub: False
      hub_model_id: tmp
      hub_private_repo: True
      completion_only_loss: True
      batch_eval_metrics: True

evaluation:
  decision_threshold: 0.02
